---
# tasks file for system
- name: Update apt cache
  apt: update_cache=yes

- name: Checking essentials
  apt:
    name: "{{ item }}"
    state: present
  with_items:
  - python-software-properties
  - python-pycurl
  - build-essential
  - python-pip
  - python-mysqldb
  - curl
  - git-core
  - dbus

- name: Install pexpect
  pip: name=pexpect

- name: Enable UFW
  ufw: state=enabled rule=allow name=OpenSSH