---
# tasks file for mariadb
- name: MariaDB | Install MariaDB.
  apt: name=mariadb-server state=present

- name: Install MySQLdb Python package for secure installations.
  apt: name=python-mysqldb state=present

# - name: MariaDB | mysql_secure_installation
#   expect:
#     command: mysql_secure_installation
#     responses:
#       "Enter current password for root": "{{mysql_root_password}}"
#       "Change the root password" : "n"
#       "Remove anonymous users": "y"
#       "Disallow root login remotely": "y"
#       "Remove test database": "y"
#       "Reload privilege tables": "y"

# 'localhost' needs to be the last item for idempotency.
- name: mysql_secure_installation | Change the root password
  mysql_user: name=root host={{ item }} password={{ mysql_root_password }}
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: mysql_secure_installation | Copy .my.cnf file with root password credentials
  template: src=roles/mariadb/templates/.my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600

- name: mysql_secure_installation | Remove anonymous users.
  mysql_user: name="" host={{ item }} state="absent"
  with_items:
    - "{{ ansible_hostname }}"
    - localhost

- name: mysql_secure_installation | Remove test database.
  mysql_db: name=test state=absent